class_name PageView
extends Control
## Self-contained coloring page: paper + GPU-clipped paint layer + line art,
## with pan/zoom and the region-locked stroke lifecycle (DESIGN.md 3.2/3.3).
##
## The component knows nothing about which page it shows. A parent injects the
## page either by setting the exported paths before it enters the tree, or by
## calling [method load_page] at any time.
##
## Signals go UP (a parent listens), calls come DOWN (a parent sets
## [member brush_color] / [member brush_size] and calls methods). This node never
## reaches out of its own subtree.
##
## Layer order, back to front: paper -> paint SubViewport texture -> line art ->
## debug overlay.

## Emitted once a page's textures and region data are in place.
signal page_loaded(page_size: Vector2i)
## Emitted on press, after a region has been locked for the whole stroke.
signal region_locked(region_id: int)
## Emitted when a stroke finishes (normally or cancelled). M4 hooks per-region
## coverage tracking here; M2 only fires the hook.
signal stroke_ended(region_id: int)
## Emitted, before [signal stroke_ended], when a stroke is aborted rather than
## released -- e.g. a second finger landing mid-stroke. Paint already committed
## stays on the page.
signal stroke_cancelled(region_id: int)

const BRUSH_SHADER: Shader = preload("res://scenes/components/brush.gdshader")
const LINE_ART_SHADER: Shader = preload("res://scenes/components/line_art.gdshader")

## Distance between brush dabs, as a fraction of the brush RADIUS. 0.25 means a
## dab every quarter radius, so consecutive dabs overlap by ~87% of their width:
## fast drags cannot leave gaps.
const STAMP_SPACING_RATIO := 0.25
## Floor for the above, so a hairline brush cannot request thousands of dabs.
const MIN_STAMP_SPACING_PX := 0.75
## Hard cap on dabs generated by a single drag event (a teleporting pointer must
## not stall the frame).
const MAX_STAMPS_PER_EVENT := 512
## Multiplicative zoom per mouse-wheel notch.
const WHEEL_ZOOM_STEP := 1.15
## Reserved ID-map value: line art / not paintable.
const UNPAINTABLE_ID := 0
## Returned by [method get_region_id_at] outside the page.
const OUT_OF_BOUNDS_ID := -1

# ------------------------------------------------------------- page injection --

@export_group("Page")
## Line-art PNG. Injected by the parent; empty in the component itself.
@export_file("*.png") var base_image_path: String = ""
## Region ID-map PNG (lossless, id = R<<16|G<<8|B, #000000 = lines).
@export_file("*.png") var id_map_path: String = ""
## Region polygons JSON (schema v1).
@export_file("*.json") var regions_json_path: String = ""
## Load the paths above automatically in [method _ready].
@export var auto_load_on_ready: bool = true

@export_group("Brush")
## Colour laid down by the next stroke.
@export var brush_color: Color = Color("ef6f4a")
## Brush DIAMETER in page pixels.
@export_range(2.0, 512.0, 0.5) var brush_size: float = 56.0:
	set(value):
		brush_size = maxf(value, 1.0)
## 0 = fully feathered dab, 1 = hard dab. Never affects the region clip, which is
## always hard-edged.
@export_range(0.0, 1.0, 0.01) var brush_hardness: float = 0.85

@export_group("Appearance")
## Paper shown behind the paint layer.
@export var paper_color: Color = Color.WHITE:
	set(value):
		paper_color = value
		if is_instance_valid(_paper):
			_paper.modulate = value
## Turn white paper in the line-art PNG into transparency so the paint layer
## shows through. Off for art that is already "dark lines on transparent".
@export var line_art_white_to_alpha: bool = true:
	set(value):
		line_art_white_to_alpha = value
		_apply_line_art_material()

@export_group("View")
## Smallest zoom, as a multiple of the fit-to-view zoom.
@export_range(0.05, 1.0, 0.01) var min_zoom_factor: float = 0.5
## Largest zoom, as a multiple of the fit-to-view zoom.
@export_range(1.0, 64.0, 0.1) var max_zoom_factor: float = 8.0
## Opacity of the whole debug overlay (see [method set_debug_overlay_visible]).
@export_range(0.0, 1.0, 0.01) var debug_overlay_alpha: float = 0.45

# ------------------------------------------------------------- node handles --

@onready var _paint_viewport: SubViewport = $PaintViewport
@onready var _paint_canvas: PaintCanvas = $PaintViewport/PaintCanvas
@onready var _page_root: Node2D = $PageRoot
@onready var _paper: Sprite2D = $PageRoot/Paper
@onready var _paint_sprite: Sprite2D = $PageRoot/PaintSprite
@onready var _line_art_sprite: Sprite2D = $PageRoot/LineArtSprite
@onready var _debug_overlay: Node2D = $PageRoot/DebugOverlay

# ------------------------------------------------------------ runtime state --

var _loaded := false
var _page_size := Vector2i.ZERO
## CPU copy of the ID map, used for press-time hit-testing (DESIGN.md 3.1).
var _id_image: Image
var _id_texture: Texture2D
## Region records: { id, id_color: Color, outline, holes, centroid, area_px }.
var _regions: Array[Dictionary] = []
var _regions_by_id: Dictionary = {}

var _stroke_active := false
var _locked_region_id := UNPAINTABLE_ID
var _locked_id_color := Vector3.ZERO
var _stroke_touch_index := -1
var _last_stamp_position := Vector2.ZERO
var _last_pointer_position := Vector2.ZERO

## index -> position, in viewport coordinates. Drives the two-finger rules.
var _touches: Dictionary = {}
var _pinch_active := false
var _pinch_previous_distance := 0.0
var _pinch_previous_midpoint := Vector2.ZERO
var _middle_panning := false

var _fit_zoom := 1.0
## Set once the player pans/zooms, so a window resize stops re-fitting the page.
var _view_user_adjusted := false


func _ready() -> void:
	# Events must reach _unhandled_input (one touch code path), so the component
	# does not swallow them in the GUI phase.
	mouse_filter = Control.MOUSE_FILTER_IGNORE
	clip_contents = true
	_debug_overlay.visible = false
	resized.connect(_on_resized)
	if auto_load_on_ready and base_image_path != "" and id_map_path != "":
		load_page(base_image_path, id_map_path, regions_json_path)


# =============================================================== page loading ==

## Loads a page. Returns false and pushes an error if anything is missing or the
## ID map does not match the base image.
func load_page(base_path: String, idmap_path: String, regions_path: String) -> bool:
	_loaded = false
	cancel_stroke()

	var base_texture := load(base_path) as Texture2D
	if base_texture == null:
		push_error("PageView: cannot load base image '%s'." % base_path)
		return false
	_id_texture = load(idmap_path) as Texture2D
	if _id_texture == null:
		push_error("PageView: cannot load ID map '%s'." % idmap_path)
		return false

	_id_image = _id_texture.get_image()
	if _id_image == null:
		push_error("PageView: ID map '%s' has no readable image data." % idmap_path)
		return false
	if _id_image.is_compressed():
		# Would mean the .import settings lost compress/mode=0 (see DESIGN.md 3.2).
		push_warning("PageView: ID map '%s' is VRAM-compressed; region ids may be corrupt." % idmap_path)
		_id_image = _id_image.duplicate()
		_id_image.decompress()

	_page_size = Vector2i(base_texture.get_width(), base_texture.get_height())
	if Vector2i(_id_image.get_width(), _id_image.get_height()) != _page_size:
		push_error(
			"PageView: ID map size %s does not match base image size %s."
			% [Vector2i(_id_image.get_width(), _id_image.get_height()), _page_size]
		)
		return false

	_regions = _load_regions(regions_path)

	var page_size_f := Vector2(_page_size)

	# Paint layer: a SubViewport the size of the page whose render target is
	# never cleared, so strokes persist across frames.
	_paint_viewport.size = _page_size
	_paint_viewport.transparent_bg = true
	_paint_viewport.disable_3d = true
	_paint_viewport.gui_disable_input = true
	_paint_viewport.handle_input_locally = false
	_paint_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ONCE
	_paint_viewport.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	_paint_canvas.configure(BRUSH_SHADER, _id_texture, page_size_f)

	_paper.texture = _make_white_texture()
	_paper.centered = false
	_paper.scale = page_size_f
	_paper.modulate = paper_color

	_paint_sprite.centered = false
	_paint_sprite.texture = _paint_viewport.get_texture()

	_line_art_sprite.centered = false
	_line_art_sprite.texture = base_texture
	_apply_line_art_material()

	_build_debug_overlay()

	_loaded = true
	_view_user_adjusted = false
	fit_page_to_view()
	page_loaded.emit(_page_size)
	return true


func _load_regions(regions_path: String) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	_regions_by_id = {}
	if regions_path == "":
		return result
	if not FileAccess.file_exists(regions_path):
		push_warning("PageView: regions JSON '%s' not found; overlay/centroids unavailable." % regions_path)
		return result
	var text := FileAccess.get_file_as_string(regions_path)
	var parsed: Variant = JSON.parse_string(text)
	if typeof(parsed) != TYPE_DICTIONARY:
		push_warning("PageView: regions JSON '%s' is not an object." % regions_path)
		return result
	var data: Dictionary = parsed
	if int(data.get("version", 0)) != 1:
		push_warning("PageView: regions JSON '%s' has unsupported version %s." % [regions_path, data.get("version")])
	for entry_variant in data.get("regions", []):
		var entry: Dictionary = entry_variant
		var record := {
			"id": int(entry.get("id", 0)),
			"id_color": Color(String(entry.get("id_color", "#000000"))),
			"outline": _to_points(entry.get("outline", [])),
			"holes": _to_point_lists(entry.get("holes", [])),
			"centroid": _to_point(entry.get("centroid", [0, 0])),
			"area_px": int(entry.get("area_px", 0)),
		}
		result.append(record)
		_regions_by_id[record["id"]] = record
	return result


static func _to_point(value: Variant) -> Vector2:
	var pair: Array = value
	return Vector2(float(pair[0]), float(pair[1]))


static func _to_points(value: Variant) -> PackedVector2Array:
	var points := PackedVector2Array()
	for pair in value:
		points.append(_to_point(pair))
	return points


static func _to_point_lists(value: Variant) -> Array[PackedVector2Array]:
	var lists: Array[PackedVector2Array] = []
	for entry in value:
		lists.append(_to_points(entry))
	return lists


static func _make_white_texture() -> ImageTexture:
	var image := Image.create(1, 1, false, Image.FORMAT_RGBA8)
	image.fill(Color.WHITE)
	return ImageTexture.create_from_image(image)


func _apply_line_art_material() -> void:
	if not is_instance_valid(_line_art_sprite):
		return
	var shader_material := _line_art_sprite.material as ShaderMaterial
	if shader_material == null:
		shader_material = ShaderMaterial.new()
		shader_material.shader = LINE_ART_SHADER
		_line_art_sprite.material = shader_material
	shader_material.set_shader_parameter("white_to_alpha", line_art_white_to_alpha)


# ================================================================ region data ==

## Region id at a page pixel. [constant UNPAINTABLE_ID] for line art,
## [constant OUT_OF_BOUNDS_ID] outside the page.
func get_region_id_at(page_position: Vector2) -> int:
	if _id_image == null:
		return OUT_OF_BOUNDS_ID
	var x := int(floor(page_position.x))
	var y := int(floor(page_position.y))
	if x < 0 or y < 0 or x >= _page_size.x or y >= _page_size.y:
		return OUT_OF_BOUNDS_ID
	var pixel := _id_image.get_pixel(x, y)
	return (pixel.r8 << 16) | (pixel.g8 << 8) | pixel.b8


## Ids of every region in the page's JSON, in file order.
func get_region_ids() -> PackedInt32Array:
	var ids := PackedInt32Array()
	for region in _regions:
		ids.append(region["id"])
	return ids


## A copy of one region's record ({ id, id_color, outline, holes, centroid,
## area_px }), or an empty dictionary. For overlays, hint markers and (M4)
## coverage sample grids -- never for the paint clip, which uses the ID map.
func get_region_data(region_id: int) -> Dictionary:
	if not _regions_by_id.has(region_id):
		return {}
	return (_regions_by_id[region_id] as Dictionary).duplicate(true)


func get_page_size() -> Vector2i:
	return _page_size


func is_page_loaded() -> bool:
	return _loaded


## The CPU-side ID map. Treat as read-only.
func get_id_map_image() -> Image:
	return _id_image


# =========================================================== stroke lifecycle ==

## Press. Locks the region under [param page_position] for the WHOLE stroke and
## lays the first dab. Returns false (and starts nothing) on line art or outside
## the page. The input path and automated tests both go through here.
func begin_stroke(page_position: Vector2) -> bool:
	if not _loaded:
		return false
	if _stroke_active:
		end_stroke()
	var region_id := get_region_id_at(page_position)
	if region_id <= UNPAINTABLE_ID:
		return false

	var pixel := _id_image.get_pixel(int(page_position.x), int(page_position.y))
	# Raw texel values, matching exactly what the shader samples from the ID map.
	_locked_id_color = Vector3(pixel.r8 / 255.0, pixel.g8 / 255.0, pixel.b8 / 255.0)
	_locked_region_id = region_id
	_stroke_active = true
	_last_stamp_position = page_position
	_last_pointer_position = page_position
	_stamp(PackedVector2Array([page_position]))
	region_locked.emit(region_id)
	return true


## Drag. Interpolates dabs from the previous stamp up to [param page_position].
## The locked region is NEVER re-evaluated, so the pointer may wander anywhere.
func continue_stroke(page_position: Vector2) -> void:
	if not _stroke_active:
		return
	_last_pointer_position = page_position
	var spacing := maxf(_brush_radius() * STAMP_SPACING_RATIO, MIN_STAMP_SPACING_PX)
	var travel := _last_stamp_position.distance_to(page_position)
	if travel < spacing:
		return
	var count := mini(int(floor(travel / spacing)), MAX_STAMPS_PER_EVENT)
	var points := PackedVector2Array()
	var direction := (page_position - _last_stamp_position) / travel
	for i in range(1, count + 1):
		points.append(_last_stamp_position + direction * (spacing * i))
	_last_stamp_position = points[points.size() - 1]
	_stamp(points)


## Release. Lays a final dab at the last pointer position, then ends the stroke.
func end_stroke() -> void:
	if not _stroke_active:
		return
	if _last_stamp_position.distance_to(_last_pointer_position) > 0.01:
		_stamp(PackedVector2Array([_last_pointer_position]))
	var region_id := _locked_region_id
	_stroke_active = false
	_stroke_touch_index = -1
	_locked_region_id = UNPAINTABLE_ID
	stroke_ended.emit(region_id)


## Aborts an in-progress stroke (a second finger landed). Paint already committed
## to the SubViewport stays -- only further painting stops.
func cancel_stroke() -> void:
	if not _stroke_active:
		return
	var region_id := _locked_region_id
	_stroke_active = false
	_stroke_touch_index = -1
	_locked_region_id = UNPAINTABLE_ID
	stroke_cancelled.emit(region_id)
	stroke_ended.emit(region_id)


func is_stroke_active() -> bool:
	return _stroke_active


## Region locked by the current stroke, or [constant UNPAINTABLE_ID] when idle.
func get_locked_region_id() -> int:
	return _locked_region_id


func _brush_radius() -> float:
	return maxf(brush_size * 0.5, 0.5)


func _stamp(points: PackedVector2Array) -> void:
	_paint_canvas.queue_stamps(
		points, _brush_radius(), brush_color, _locked_id_color, brush_hardness
	)


# =============================================================== paint access ==

## Wipes the paint layer (the SubViewport clears itself on the next render).
func clear_paint() -> void:
	cancel_stroke()
	if not _loaded:
		return
	_paint_canvas.discard_pending()
	_paint_viewport.render_target_clear_mode = SubViewport.CLEAR_MODE_ONCE


## Reads the paint layer back to the CPU. Expensive -- debug/verification only;
## M4 coverage must sample sparsely instead (coloring-mechanics skill).
func get_paint_image() -> Image:
	if not _loaded:
		return null
	return _paint_viewport.get_texture().get_image()


## True while stamps are queued but not yet rendered into the SubViewport.
func has_pending_paint() -> bool:
	return _loaded and _paint_canvas.has_pending()


# ============================================================== debug overlay ==

## Region tinting from the JSON polygons (DESIGN.md 4). Off by default.
##
## Holes are handled by the painter's algorithm rather than by cutting polygons:
## regions are drawn largest-area-first with OPAQUE fills, and the whole overlay
## is faded with [member debug_overlay_alpha]. Because every hole in a region is
## filled by a smaller region (or by line art), the smallest region covering a
## pixel is always the last one drawn there, so each pixel shows its own region's
## exact tint -- no blended mixture, no polygon boolean ops. The one case this
## approximates is a hole bounded only by line art with no region inside it: it
## takes the parent's tint. The line art still renders under the faded overlay.
func set_debug_overlay_visible(is_visible: bool) -> void:
	_debug_overlay.visible = is_visible


func is_debug_overlay_visible() -> bool:
	return _debug_overlay.visible


func toggle_debug_overlay() -> bool:
	_debug_overlay.visible = not _debug_overlay.visible
	return _debug_overlay.visible


func _build_debug_overlay() -> void:
	for child in _debug_overlay.get_children():
		_debug_overlay.remove_child(child)
		child.queue_free()
	_debug_overlay.modulate = Color(1.0, 1.0, 1.0, debug_overlay_alpha)
	var ordered := _regions.duplicate()
	ordered.sort_custom(func(a: Dictionary, b: Dictionary) -> bool:
		return int(a["area_px"]) > int(b["area_px"])
	)
	for region in ordered:
		var outline: PackedVector2Array = region["outline"]
		if outline.size() < 3:
			continue
		var polygon := Polygon2D.new()
		polygon.name = "Region%d" % int(region["id"])
		polygon.polygon = outline
		polygon.color = _region_tint(int(region["id"]))
		_debug_overlay.add_child(polygon)


## Deterministic, well-spread hue per id (golden-ratio rotation).
static func _region_tint(region_id: int) -> Color:
	return Color.from_hsv(fmod(float(region_id) * 0.6180339887, 1.0), 0.72, 1.0, 1.0)


# ==================================================================== the view ==

## Page pixel coordinates for a position in viewport (input event) coordinates.
## Correct under any pan/zoom, and under a scaled UI canvas.
func to_page_position(viewport_position: Vector2) -> Vector2:
	return _page_root.get_global_transform_with_canvas().affine_inverse() * viewport_position


## Inverse of [method to_page_position]: viewport coordinates for a page pixel.
## Useful for placing UI on top of the page (hint markers, tooltips).
func to_viewport_position(page_position: Vector2) -> Vector2:
	return _page_root.get_global_transform_with_canvas() * page_position


func get_zoom() -> float:
	return _page_root.scale.x


## Centres the page and scales it to fit, and resets the zoom limits around that.
func fit_page_to_view() -> void:
	if not _loaded or size.x <= 0.0 or size.y <= 0.0:
		return
	_fit_zoom = minf(size.x / float(_page_size.x), size.y / float(_page_size.y))
	if _fit_zoom <= 0.0:
		_fit_zoom = 1.0
	_page_root.scale = Vector2(_fit_zoom, _fit_zoom)
	_page_root.position = (size - Vector2(_page_size) * _fit_zoom) * 0.5
	_view_user_adjusted = false


func reset_view() -> void:
	fit_page_to_view()


func _on_resized() -> void:
	if not _loaded:
		return
	var previous_fit := _fit_zoom
	_fit_zoom = maxf(minf(size.x / float(_page_size.x), size.y / float(_page_size.y)), 0.0001)
	if _view_user_adjusted:
		# Keep the player's framing, just re-clamp against the new limits.
		if previous_fit > 0.0:
			_apply_zoom(_page_root.scale.x * (_fit_zoom / previous_fit), size * 0.5)
		_clamp_view()
	else:
		fit_page_to_view()


func _min_zoom() -> float:
	return _fit_zoom * min_zoom_factor


func _max_zoom() -> float:
	return _fit_zoom * max_zoom_factor


## Zooms to [param target_zoom] keeping [param anchor] (viewport coordinates)
## over the same page pixel.
func _apply_zoom(target_zoom: float, anchor: Vector2) -> void:
	var clamped := clampf(target_zoom, _min_zoom(), _max_zoom())
	if is_equal_approx(clamped, _page_root.scale.x):
		return
	var page_before := to_page_position(anchor)
	_page_root.scale = Vector2(clamped, clamped)
	var page_after := to_page_position(anchor)
	_page_root.position += (page_after - page_before) * clamped
	_view_user_adjusted = true
	_clamp_view()


func _pan_by(viewport_delta: Vector2) -> void:
	var local_delta := get_global_transform_with_canvas().affine_inverse().basis_xform(viewport_delta)
	_page_root.position += local_delta
	_view_user_adjusted = true
	_clamp_view()


## Keeps the page's centre inside the view so it can never be flung off-screen.
func _clamp_view() -> void:
	var extent := Vector2(_page_size) * _page_root.scale.x
	var page_center := _page_root.position + extent * 0.5
	var clamped := Vector2(
		clampf(page_center.x, 0.0, size.x),
		clampf(page_center.y, 0.0, size.y)
	)
	_page_root.position += clamped - page_center


func _contains_viewport_position(viewport_position: Vector2) -> bool:
	var local := get_global_transform_with_canvas().affine_inverse() * viewport_position
	return Rect2(Vector2.ZERO, size).has_point(local)


# ======================================================================= input ==
# One code path: touch. "Emulate Touch From Mouse" is on in project settings, so
# a left-click drag arrives here as InputEventScreenTouch/Drag. Only wheel-zoom
# and middle-drag pan read mouse events, because those have no touch equivalent.

func _unhandled_input(event: InputEvent) -> void:
	if not _loaded:
		return
	if event is InputEventScreenTouch:
		_handle_touch(event)
	elif event is InputEventScreenDrag:
		_handle_drag(event)
	elif event is InputEventMouseButton:
		_handle_mouse_button(event)
	elif event is InputEventMouseMotion:
		_handle_mouse_motion(event)


func _handle_touch(event: InputEventScreenTouch) -> void:
	if event.pressed:
		if not _contains_viewport_position(event.position) and _touches.is_empty():
			return
		_touches[event.index] = event.position
		if _touches.size() >= 2:
			# Second finger: this is a pan/zoom gesture, not a stroke. Abort the
			# accidental one-finger stroke (already-painted pixels stay).
			cancel_stroke()
			_begin_pinch()
			get_viewport().set_input_as_handled()
			return
		if begin_stroke(to_page_position(event.position)):
			_stroke_touch_index = event.index
			get_viewport().set_input_as_handled()
	else:
		_touches.erase(event.index)
		if _touches.size() < 2:
			_pinch_active = false
			_pinch_previous_distance = 0.0
		if _stroke_active and event.index == _stroke_touch_index:
			end_stroke()


func _handle_drag(event: InputEventScreenDrag) -> void:
	_touches[event.index] = event.position
	if _pinch_active and _touches.size() >= 2:
		_update_pinch()
		get_viewport().set_input_as_handled()
		return
	if _stroke_active and event.index == _stroke_touch_index:
		continue_stroke(to_page_position(event.position))
		get_viewport().set_input_as_handled()


func _begin_pinch() -> void:
	var indices := _touches.keys()
	indices.sort()
	if indices.size() < 2:
		return
	var first: Vector2 = _touches[indices[0]]
	var second: Vector2 = _touches[indices[1]]
	_pinch_previous_distance = first.distance_to(second)
	_pinch_previous_midpoint = (first + second) * 0.5
	_pinch_active = true


func _update_pinch() -> void:
	var indices := _touches.keys()
	indices.sort()
	if indices.size() < 2:
		return
	var first: Vector2 = _touches[indices[0]]
	var second: Vector2 = _touches[indices[1]]
	var distance := first.distance_to(second)
	var midpoint := (first + second) * 0.5
	if _pinch_previous_distance > 1.0 and distance > 1.0:
		_apply_zoom(_page_root.scale.x * (distance / _pinch_previous_distance), midpoint)
	_pan_by(midpoint - _pinch_previous_midpoint)
	_pinch_previous_distance = distance
	_pinch_previous_midpoint = midpoint


func _handle_mouse_button(event: InputEventMouseButton) -> void:
	match event.button_index:
		MOUSE_BUTTON_WHEEL_UP:
			if event.pressed and _contains_viewport_position(event.position):
				_apply_zoom(_page_root.scale.x * WHEEL_ZOOM_STEP, event.position)
				get_viewport().set_input_as_handled()
		MOUSE_BUTTON_WHEEL_DOWN:
			if event.pressed and _contains_viewport_position(event.position):
				_apply_zoom(_page_root.scale.x / WHEEL_ZOOM_STEP, event.position)
				get_viewport().set_input_as_handled()
		MOUSE_BUTTON_MIDDLE:
			if event.pressed and not _contains_viewport_position(event.position):
				return
			_middle_panning = event.pressed
			if event.pressed:
				cancel_stroke()
			get_viewport().set_input_as_handled()


func _handle_mouse_motion(event: InputEventMouseMotion) -> void:
	if _middle_panning:
		_pan_by(event.relative)
		get_viewport().set_input_as_handled()
